Ecommerce/urls.py
from django.contrib.auth import views as auth_views
from django.http import HttpResponseRedirect
from django.urls import path, re_path, reverse

from . import views

app_name = "ecommerce"

urlpatterns = [
    path('', views.home.as_view(), name="home"),
    path('subscribe-email/', views.subscribe_email, name="subscribe_email"),
    # ---------------------- User management ----------------------
    path('account/', views.account, name="account"),
    path('login/', views.login_user, name="login"),
    path('logout/', views.log_out_user, name="logout"),
    # ---------------------- Delete from cart ----------------------
    path('delete_cart/', views.delete_cart, name="delete_cart"),
    # ---------------------- Add to wish list----------------------
    path('add-wish-list/', views.add_wish, name='add_to_wish_list'),
    # ---------------------- Add to cart ----------------------
    path('add-cart/', views.add_cart, name='add_to_cart'),
    # ---------------------- Compare list ----------------------
    path('compare-list/', views.compare_list, name='compare_list'),
    # ---------------------- Add to compare list ----------------------
    path('add-compare/', views.add_compare, name='add_to_compare'),
    # ---------------------- Delete from compare list----------------------
    path('delete-product-compare/', views.delete_product_compare, name='delete_from_compare'),
    # ---------------------- Load more carts----------------------
    path('load_carts/', views.load_carts, name='load_carts'),
    # ---------------------- Contact us ----------------------
    path('contact-us/', views.contact_us, name='contact_us'),
    # ---------------------- All products ----------------------
    path('products/', views.products, name='products'),
    # ---------------------- Category products----------------------
    path('category/products/<int:category_id>/', views.products, name='category_products'),
    # ---------------------- Single product ----------------------
    path('product/<int:product_id>/', views.product, name='product'),
    # ---------------------- COMMANDS TRACKER ----------------------
    path('commands-tracker/', views.product, name='commands_tracker'),
    # ---------------------- Wish list ----------------------
    path('wish-list/', views.WishListView.as_view(), name='wish_list'),
    # ---------------------- Delete wish list ----------------------
    path('remove-wish-list/', views.RemoveWishListView.as_view(), name='remove_wish_list'),
    # ---------------------- brand products ----------------------
    path('brand/products/<int:brand_id>/', views.products, name='brand_products'),
    # ---------------------- brand products ----------------------
    path('cart/', views.CartView.as_view(), name='cart'),
    # ---------------------- brand products ----------------------
    path('cart-update/', views.UpdateCartView.as_view(), name='update_cart'),
    # ---------------------- Checkout ----------------------
    path('checkout/', views.CheckOutView.as_view(), name='checkout'),
    # ---------------------- Checkout ----------------------
    path('checkouts/', views.CheckOutsView.as_view(), name='checkouts'),
    # ---------------------- Checkout ----------------------
    path('cash-checkout/', views.CashCheckout.as_view(), name='cash_checkout'),
    # ---------------------- Checkout ----------------------
    path('checkout/process', views.ProcessPayment.as_view(), name='process_payment'),
    # ---------------------- Payment Done ----------------------
    path('payment-done/', views.PaymentDone.as_view(), name='payment_done'),
    # ---------------------- Payment Cancelled ----------------------
    path('payment-cancelled/', views.PaymentCancelled.as_view(), name='payment_cancelled'),
    # ---------------------- Payment Cancelled ----------------------
    path('track-your-order/', views.TrackOrder.as_view(), name='track_your_order'),
    # ---------------------- Sign up Process Handlet ----------------------
    path('signup-complete/', views.signup_complete, name='signup_complete'),
    path('confirm-email/<int:id_user>/<str:token_email>/', views.confirm_email_signup, name='confirm_email_signup'),
    path('confirm_mail/resend/', views.ConfirmMailResendView.as_view(), name='confirm_mail_resend'),
    # ---------------------- Reset Password Handler ----------------------
    path('reset-password/', views.password_reset, name='password_reset'),
    path('reset-password/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    re_path('reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
            auth_views.PasswordResetConfirmView.as_view(template_name="ecommerce/registration/password_reset_confirm.html",
                                                        success_url='/ecommerce/reset-password/complete/'),
            name='password_reset_confirm'),
    path('reset-password/complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='ecommerce/registration/password_reset_complete.html'),
         name='password_reset_complete'),

]

WebPlatform/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls import handler404, handler500

import Ecommerce

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Ecommerce.urls')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
    # ---------------------- Paypal ----------------------
    path('paypal/', include('paypal.standard.ipn.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Ecommerce/models.py
import os
import time
import uuid

from ckeditor.fields import RichTextField
from colorful.fields import RGBColorField
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone
# Create your models here.
from django.utils.deconstruct import deconstructible
from django.utils.timezone import now


@deconstructible
class PathAndRename(object):
    def __init__(self, sub_path):
        self.path = sub_path

    def __call__(self, instance, filename):
        # eg: filename = 'my uploaded file.jpg'
        ext = filename.split('.')[-1]  # eg: 'jpg'
        uid = uuid.uuid4().hex[:10]  # eg: '567ae32f97'

        # eg: 'my-uploaded-file'
        new_name = '-'.join(filename.replace('.%s' % ext, '').split())

        # eg: 'my-uploaded-file_64c942aa64.jpg'
        renamed_filename = '%(new_name)s_%(uid)s.%(ext)s' % {'new_name': new_name, 'uid': uid, 'ext': ext}

        # eg: 'images/2017/01/29/my-uploaded-file_64c942aa64.jpg'
        return os.path.join(self.path, renamed_filename)


class Image(models.Model):
    name = models.CharField(null=False, blank=False, max_length=6000, unique=True)
    upload_date = models.DateTimeField(default=timezone.now)
    image_path = time.strftime('images/%Y/%m/%d')
    file = models.FileField(upload_to=PathAndRename(image_path))

    def __str__(self):
        return self.name + " | " + self.file.name


class Category(models.Model):
    name = models.CharField(blank=False, null=False, max_length=60, unique=True)
    image = models.ForeignKey(Image, on_delete=models.CASCADE)
    icon = models.CharField(blank=True, null=True, max_length=450)

    def __str__(self):
        return "Category: " + self.name

    def get_absolute_url(self):
        return reverse("ecommerce:category_products", kwargs={'category_id': self.id})


class Brand(models.Model):
    name = models.CharField(max_length=300)
    description = RichTextField(max_length=15000, null=True, blank=True)
    logo = models.ForeignKey(Image, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return "Brand(Company): " + self.name

    def get_absolute_url(self):
        return reverse("ecommerce:brand_products", kwargs={'brand_id': self.id})


rates = ((1, 1), (2, 2), (3, 3), (4, 4), (5, 5))


class Product(models.Model):
    name = models.CharField(max_length=255, null=False, blank=False, unique=True)
    price = models.DecimalField(max_digits=15, decimal_places=2, null=False, blank=False)
    images = models.ManyToManyField(Image, blank=False)
    add_date = models.DateTimeField(default=timezone.now)
    categories = models.ManyToManyField(Category, blank=True)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    old_price = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    is_active = models.BooleanField(default=True)
    number_views = models.IntegerField(default=0)
    rate = models.IntegerField(null=True, blank=True, choices=rates)
    quantity_min = models.IntegerField(default=1, null=True, blank=True)
    # Offre spéciale (oui | non)
    is_featured = models.BooleanField(default=False)
    price_from = models.DecimalField(blank=True, max_digits=16, decimal_places=2, null=True)

    def __str__(self):
        return "Product: " + self.name + " | Price: " + str(self.price)

    def get_absolute_url(self):
        return reverse('ecommerce:product', kwargs={'product_id': self.id})

    def rating(self):
        rate = self.rate if self.rate is not None else 0
        return rate * 20


class Description(models.Model):
    text = RichTextField()
    product = models.OneToOneField(Product, blank=False, null=False, on_delete=models.CASCADE)

    def __str__(self):
        return f"Description of: {self.product}"


class Specification(models.Model):
    text = models.TextField(max_length=60000, null=True, blank=True)
    product = models.ForeignKey(Product, blank=True, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return "{} : {}".format(self.text, self.text[:200])


class Color(models.Model):
    code_hex = RGBColorField()

    def __str__(self):
        if self.code_hex is not None:
            return self.code_hex
        return "#FFFFFF"


class Stock(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=0, null=False, blank=False)
    color = models.ForeignKey(Color, on_delete=models.CASCADE, blank=True, null=True)
    first_quantity = models.IntegerField(default=0)
    price_sup = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True, default=0)

    def __str__(self):
        return "Product: " + str(self.product.name) + " | Quantity: " + str(self.quantity) + " | Color: " + str(
            self.color)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    picture = models.ForeignKey(Image, on_delete=models.CASCADE)
    token_email = models.CharField(max_length=300, blank=True, null=True, default="")
    token_email_expiration = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return "User: " + self.user.first_name + " " + self.user.last_name

    def full_name(self):
        return f"{self.user.first_name} {self.user.last_name}"


# Offres
class Sale(models.Model):
    percentage = models.IntegerField()
    date_end = models.DateTimeField(blank=False, default=timezone.now)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    is_daily = models.BooleanField(default=False)

    def __str__(self):
        return str(self.percentage) + "% for " + self.product.name

    def new_price(self):
        return self.product.price - ((self.product.price * self.percentage) / 100)

    def saved_amount(self):
        return ((self.product.price * self.percentage) / 100)

    def rating(self):
        return (self.product.rate * 100) / 5


class Compare(models.Model):
    products = models.ManyToManyField(Product)
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)

    def __str__(self):
        return "Products To Compare: " + str(self.products.all().count())


class WishList(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    def __str__(self):
        return self.profile.user.username + ' ' + self.product.name

delivery_method = (('Free Shipping', 'Free Shipping'), ('Flat Shipping Rate', 'Flat Shipping Rate'))
payment_method = (('1', 'Cash On Delivery'), ('2', 'Paypal'))
class Order(models.Model):
    amount = models.DecimalField(max_digits=15, decimal_places=2)
    date = models.DateField(auto_now_add=True)
    status = models.CharField(max_length=200, default="Created")
    comment = models.TextField(null=False, blank=True, default="")
    track_number = models.CharField(max_length=300, null=True, blank=True)
    date_payment = models.DateField(null=True, blank=True)
    date_complete = models.DateField(null=True, blank=True)
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True)
    payment_method = models.CharField(max_length=20, choices=payment_method, default='Cash On Delivery')
    delivery_method = models.CharField(max_length=20, choices=delivery_method, default='Free Shipping')
    company = models.CharField(max_length=254, blank=True)
    address = models.TextField()
    city = models.CharField(max_length=254)
    zipcode = models.CharField(max_length=254)
    country = models.CharField(max_length=254)
    state = models.CharField(max_length=254)

    def __str__(self):
        return 'Order {0} de {1}'.format(str(self.pk), self.profile.user.username)


class OrderLine(models.Model):
    quantity = models.IntegerField()
    total = models.DecimalField(max_digits=15, decimal_places=2)
    order = models.ForeignKey(Order, on_delete=models.CASCADE, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True)
    color = models.ForeignKey(Color, on_delete=models.CASCADE, null=True)

    def price_unit(self):
        return self.total / self.quantity

    def __str__(self):
        return f"PRODUIT: {self.product} | TOTAL: {self.total} | ORDER: {self.order}"


class Cart(models.Model):
    quantity = models.IntegerField(default=1)
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True, blank=True)
    color = models.ForeignKey(Color, on_delete=models.CASCADE, null=True, blank=True)

    def total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return '{0} x {1} : {2}'.format(str(self.quantity), self.product.name, self.profile.user.username)


class Banner(models.Model):
    title = models.CharField(max_length=650)
    description = RichTextField(max_length=100000)
    price_from = models.DecimalField(max_digits=16, decimal_places=2)
    product = models.ForeignKey(Product, null=True, blank=True, on_delete=models.CASCADE)
    external_url = models.CharField(max_length=500, null=True, blank=True)
    image = models.ForeignKey(Image, on_delete=models.CASCADE, null=True, blank=True)
    is_active = models.BooleanField(default=True)
    is_approved = models.BooleanField(default=False)

    # ====================== To edit later ======================
    def get_absolut_url(self):
        if self.external_url is None:
            return reverse('ecommerce:home')
        return reverse('ecommerce:home')

    def get_rest(self):
        print(str((self.price_from % int(self.price_from)).normalize())[2:])
        return str((self.price_from % int(self.price_from)).normalize())[2:]

    def get_banner_image(self):
        if self.image is None or self.image == "":
            return self.product.images.first().file.url
        return self.image.file.url

templates/ecommerce/compare.html
{% extends 'ecommerce/base.html' %}
{% load staticfiles %}
{% load humanize %}
{% load widget_tweaks %}

{% block title %}LISTE DE COMPARAISON{% endblock %}

{% block content %}

            <div tabindex="-1" class="site-content" id="content">
                <div class="container">

                    <nav class="woocommerce-breadcrumb"><a href="{% url 'ecommerce:home' %}">Acceuil</a><span class="delimiter"><i class="fa fa-angle-right"></i></span>Compare</nav>
                    <div class="content-area" id="primary">
                        <main class="site-main" id="main">
                            <article class="post-2917 page type-page status-publish hentry" id="post-2917">
                                <div itemprop="mainContentOfPage" class="entry-content">
                                    <div class="table-responsive">
                                        {% if compare_list_products.object_list %}
                                            <table class="table table-compare compare-list">
                                                <tbody>
                                                    <tr>
                                                        <div class="col-2">
                                                        <th>Produit</th>
                                                        </div>
                                                        {% for product in compare_list_products %}
                                                            <td product="compare_product{{ product.id }}">
                                                                <a href="{{ product.get_absolute_url }}">
                                                                    <div class="product-image">
                                                                        <a href="{{ product.images.first.file.url }}" data-fancybox data-caption="{{ product.name }}">
                                                                            <div class="">
                                                                                <img  alt="{{ product.name }}" class="attachment-shop_catalog size-shop_catalog wp-post-image" compare-image="" src="{{ product.images.first.file.url }}">
                                                                            </div>
                                                                        </a>
                                                                    </div>
                                                                    <div class="product-info">
                                                                        <a href="{{ product.get_absolute_url }}"><h3 class="product-title">{{ product.name }}</h3></a>

                                                                        <div title="Évalué {{ product.rate }} sur 5" class="star-rating"><span style="width:{{ product.rating }}%"><strong class="rating">{{ product.rate }}</strong> sur 5</span></div>
                                                                    </div>
                                                                </a><!-- /.product -->
                                                            </td>
                                                        {% endfor %}
                                                    </tr>
                                                    <tr>
                                                        <th>Prix</th>
                                                        {% for product in compare_list_products %}
                                                            <td product="compare_product{{ product.id }}">
                                                                <div class="product-price price"><span class="electro-price"><span class="amount">{{ product.price.normalize }} Dhs</span></span></div>
                                                            </td>
                                                        {% endfor %}
                                                    </tr>
                                                    <tr>
                                                        <th>Disponibilé</th>
                                                        {% for product in compare_list_products %}
                                                            {% if product.quantity_in_stock > 0 %}
                                                                <td product="compare_product{{ product.id }}"><span class="in-stock">Disponible</span></td>
                                                            {% else %}
                                                                <td product="compare_product{{ product.id }}"><span class="out-of-stock">Indisponible</span></td>
                                                            {% endif %}
                                                        {% endfor %}
                                                    </tr>
                                                    <tr>
                                                        <th>Description</th>
                                                        {% for product in compare_list_products %}
                                                            <td product="compare_product{{ product.id }}">
                                                                <ul style="text-align:left; margin-bottom: 0;" class="more-short-description{{ product.id }}" >
                                                                    {% for specification in product.specification_set.all %}
                                                                        <li {% if forloop.counter > 2 %}style="display: none;"{% endif %}><span class="a-list-item font-weight-bold">{{ specificationtext }}</span></li>
                                                                    {% empty %}
                                                                        <li><span class="a-list-item font-weight-bold">AUCUNE DESCRIPTION</span></li>
                                                                    {% endfor %}
                                                                    {% if product.specification_set.all.count > 2 %}
                                                                        <p class="maxlist-more font-weight-bold"><a href="javascript:void(0)" onclick="showMoreShortDescription(this, {{ product.id }})" >+ Afficher plus</a></p>
                                                                    {% endif %}
                                                                </ul>
                                                            </td>
                                                        {% endfor %}
                                                    </tr>
                                                    <tr>
                                                        <th>Ajouter au panier</th>
                                                        {% for product in compare_list_products %}
                                                            {% if product not in cart_products %}
                                                                <td product="compare_product{{ product.id }}" id="add_to_cart_td{{ product.id }}">
                                                                    <a button="add_cart" class="button add_to_cart_button" href="javascript:void(0)" onclick="add_to_cart(event, {{ product.id }}, '{{ product.stock_set.first.id }}', true);" rel="nofollow"><i class="fas fa-cart-arrow-down"></i><i class="fas fa-sync-alt fa-spin" style="color: #000000;display: none;"></i> Ajouter au panier</a>
                                                                </td>
                                                            {% else %}
                                                                <td product="compare_product{{ product.id }}" class="full-color-background bg-success font-weight-bold">
                                                                   <i class="fas fa-check-circle"></i> Produit éxiste déja dans votre panier
                                                                </td>
                                                            {% endif %}
                                                        {% endfor %}
                                                    </tr>
                                                    <tr>
                                                            <th>Supprimer le produit de la liste</th>
                                                            {% for product in compare_list_products %}
                                                                <td product="compare_product{{ product.id }}" class="text-center">
                                                                    <a href="javascript:void(0)" onclick="delete_from_compare(event, {{ product.id }})" title="Supprimer" class="remove-icon"><i class="fa fa-times"></i></a>
                                                                </td>
                                                            {% endfor %}
                                                        </tr>
                                                </tbody>
                                            </table>
                                        {% else %}
                                            <div class="alert alert-warning text-md-center text-uppercase font-weight-bold" style="padding: 10px;font-size:12px;font-weight:bold;width: 100%;" >
                                                <i class="fas fa-exclamation-triangle"></i>&nbsp;&nbsp;Aucun produit trouvé dans votre liste de comparaison.
                                            </div>
                                        {% endif %}
                                    </div><!-- /.table-responsive -->
                                </div><!-- .entry-content -->

                                {# ------------------ Pagination section ------------------ #}
                            {% if compare_list_products.has_other_pages %}
                                {% if compare_list_products.number > 0 %}
                                    <div class="shop-control-bar-bottom" style="text-align: center;">
                                        <nav class="woocommerce-pagination">
                                             <ul class="page-numbers">

                                                {% if compare_list_products.has_previous %}
                                                    <li>
                                                    <a href="{% url 'ecommerce:compare_list' %}?&page=1" class="previous page-numbers"><i class="fas fa-angle-double-left"></i></a></li>
                                                    <li>
                                                     <li>
                                                        <a href="{% url 'ecommerce:compare_list' %}?page={{ compare_list_products.previous_page_number }}"
                                                           class="previous page-numbers"><i class="fas fa-angle-left"></i></a>
                                                    </li>
                                                {% endif %}

                                                {% for n in compare_list_products.paginator.page_range %}
                                                    <li>
                                                        <a href="{% url 'ecommerce:compare_list' %}?page={{ n }}" class="page-numbers {% if n == wish_list.number %}current{% endif %}">{{ n }}</a>
                                                    </li>
                                                {% endfor %}

                                                {% if compare_list_products.has_next %}
                                                    <li>
                                                        <a href="{% url 'ecommerce:compare_list' %}?&page={{ compare_list_products.next_page_number }}"
                                                           class="page-numbers"><i class="fas fa-angle-right"></i></a>
                                                    </li>
                                                    <li>
                                                        <a href="{% url 'ecommerce:compare_list' %}?&page={{ compare_list_products.next_page_number }}"
                                                           class="page-numbers"><i class="fas fa-angle-double-right"></i></a>
                                                    </li>
                                                {% endif %}
                                            </ul>
                                        </nav>
                                    </div>
                                {% endif %}
                            {% endif %}
                            </article><!-- #post-## -->
                        </main><!-- #main -->
                    </div><!-- #primary -->
                </div><!-- .col-full -->
            </div>

{% endblock %}

{% block js %}
    {{ block.super }}
    <script>

    $("body").attr('class','page home page-template-default');
    $(".wp-post-image[compare-image='']").css({'height': '180', 'width':'15em'})
    </script>
{% endblock %}

templates/ecommerce/messages.html
{% if messages %}
    {% for msg in messages %}
        {% if msg.tags == "error" %}
            <div class="alert alert-danger" style="padding: 10px;font-size:12px;font-weight:bold;width: 100%;" >
                <i class="fa fa-exclamation" ></i>&nbsp;&nbsp;{{ msg | safe }}
            </div>
        {% elif msg.tags == "success" %}
            <div class="alert alert-success" style="padding: 10px;font-size:12px;font-weight:bold;width: 100%;" >
                <i class="fa fa-check-square" ></i>&nbsp;&nbsp;{{ msg | safe }}
            </div>
        {% elif msg.tags == "info" %}
            <div class="alert alert-info" style="padding: 10px;font-size:12px;font-weight:bold;width: 100%;">
                <i class="fa fa-info-circle" ></i>&nbsp;&nbsp;{{ msg | safe }}
            </div>
        {% elif msg.tags == "warning" %}
            <div class="alert alert-danger" style="padding: 10px;font-size:12px;font-weight:bold;width: 100%;" >
                <i class="fa fa-exclamation-circle" ></i>&nbsp;&nbsp;{{ msg | safe }}
            </div>
        {% else %}
            <div class="alert alert-{{ msg.tags }}" style="padding: 10px;font-size:12px;font-weight:bold;width: 100%;">
                <i class="fa fa-exclamation-triangle" ></i>&nbsp;&nbsp;{{ msg | safe }}
            </div>
        {% endif %}
    {% endfor %}
{% endif %}<br>