Ecommerce/urls.py
from django.contrib.auth import views as auth_views
from django.http import HttpResponseRedirect
from django.urls import path, re_path, reverse

from . import views

app_name = "ecommerce"

urlpatterns = [
    path('', views.home.as_view(), name="home"),
    path('subscribe-email/', views.subscribe_email, name="subscribe_email"),
    # ---------------------- User management ----------------------
    path('account/', views.account, name="account"),
    path('login/', views.login_user, name="login"),
    path('logout/', views.log_out_user, name="logout"),
    # ---------------------- Delete from cart ----------------------
    path('delete_cart/', views.delete_cart, name="delete_cart"),
    # ---------------------- Add to wish list----------------------
    path('add-wish-list/', views.add_wish, name='add_to_wish_list'),
    # ---------------------- Add to cart ----------------------
    path('add-cart/', views.add_cart, name='add_to_cart'),
    # ---------------------- Compare list ----------------------
    path('compare-list/', views.compare_list, name='compare_list'),
    # ---------------------- Add to compare list ----------------------
    path('add-compare/', views.add_compare, name='add_to_compare'),
    # ---------------------- Delete from compare list----------------------
    path('delete-product-compare/', views.delete_product_compare, name='delete_from_compare'),
    # ---------------------- Load more carts----------------------
    path('load_carts/', views.load_carts, name='load_carts'),
    # ---------------------- Contact us ----------------------
    path('contact-us/', views.contact_us, name='contact_us'),
    # ---------------------- All products ----------------------
    path('products/', views.products, name='products'),
    # ---------------------- Category products----------------------
    path('category/products/<int:category_id>/', views.products, name='category_products'),
    # ---------------------- Single product ----------------------
    path('product/<int:product_id>/', views.product, name='product'),
    # ---------------------- COMMANDS TRACKER ----------------------
    path('commands-tracker/', views.product, name='commands_tracker'),
    # ---------------------- Wish list ----------------------
    path('wish-list/', views.WishListView.as_view(), name='wish_list'),
    # ---------------------- Delete wish list ----------------------
    path('remove-wish-list/', views.RemoveWishListView.as_view(), name='remove_wish_list'),
    # ---------------------- brand products ----------------------
    path('brand/products/<int:brand_id>/', views.products, name='brand_products'),
    # ---------------------- brand products ----------------------
    path('cart/', views.CartView.as_view(), name='cart'),
    # ---------------------- brand products ----------------------
    path('cart-update/', views.UpdateCartView.as_view(), name='update_cart'),
    # ---------------------- Checkout ----------------------
    path('checkout/', views.CheckOutView.as_view(), name='checkout'),
    # ---------------------- Checkout ----------------------
    path('checkouts/', views.CheckOutsView.as_view(), name='checkouts'),
    # ---------------------- Checkout ----------------------
    path('cash-checkout/', views.CashCheckout.as_view(), name='cash_checkout'),
    # ---------------------- Checkout ----------------------
    path('checkout/process', views.ProcessPayment.as_view(), name='process_payment'),
    # ---------------------- Payment Done ----------------------
    path('payment-done/', views.PaymentDone.as_view(), name='payment_done'),
    # ---------------------- Payment Cancelled ----------------------
    path('payment-cancelled/', views.PaymentCancelled.as_view(), name='payment_cancelled'),
    # ---------------------- Payment Cancelled ----------------------
    path('track-your-order/', views.TrackOrder.as_view(), name='track_your_order'),
    # ---------------------- Sign up Process Handlet ----------------------
    path('signup-complete/', views.signup_complete, name='signup_complete'),
    path('confirm-email/<int:id_user>/<str:token_email>/', views.confirm_email_signup, name='confirm_email_signup'),
    path('confirm_mail/resend/', views.ConfirmMailResendView.as_view(), name='confirm_mail_resend'),
    # ---------------------- Reset Password Handler ----------------------
    path('reset-password/', views.password_reset, name='password_reset'),
    path('reset-password/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    re_path('reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
            auth_views.PasswordResetConfirmView.as_view(template_name="ecommerce/registration/password_reset_confirm.html",
                                                        success_url='/ecommerce/reset-password/complete/'),
            name='password_reset_confirm'),
    path('reset-password/complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='ecommerce/registration/password_reset_complete.html'),
         name='password_reset_complete'),

]

WebPlatform/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls import handler404, handler500

import Ecommerce

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Ecommerce.urls')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
    # ---------------------- Paypal ----------------------
    path('paypal/', include('paypal.standard.ipn.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Ecommerce/views.py
import decimal
from datetime import timedelta
from decimal import Decimal
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.hashers import check_password
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import send_mail
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db import models
from django.db.models import Sum, Min, F, Count, Max, Q
from django.http import JsonResponse, HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404, resolve_url
from django.template.loader import render_to_string, get_template
from django.template.response import TemplateResponse
from django.urls import reverse
from django.utils import timezone
from django.utils.crypto import get_random_string
from django.utils.decorators import method_decorator
from django.utils.timezone import now
from django.views import View
from django.views.decorators.csrf import csrf_exempt
from paypal.standard.forms import PayPalPaymentsForm
from Ecommerce.forms import LoginForm, SignUpForm, ContactForm, UserForm, UserPasswordForm, GoPageForm, PriceFilterForm, \
    CheckOutForm, TrackOrderForm, ConfirmEmailForm
from Ecommerce.models import Banner, NewsLetter, Profile, Image, WishList, Compare, Order, OrderLine
from .context_processors import *


# ---------------- HOME ----------------
class home(View):
    def get(self, request):
        context = dict()
        # ----------------SEND REQUEST THROUGH VIEW ----------------
        """
        request_url = "{0}://{1}{2}".format(request.scheme, request.get_host(), reverse('ecommerce:subscribe_email'))
        response = requests.get(request_url, params={'email': 'haytham.dahri@gmail.com'})
        print(response.json())
        """
        # ---------------- Trending Products With Min Price From ----------------
        trending_stock, trending_stock_products_ids = list(), list()
        for stock in list(Stock.objects.filter(product__is_active=True).order_by('-product__number_views')):
            if stock.product.pk not in trending_stock_products_ids:
                stock.product_min_price_from = \
                    Product.objects.filter(id=stock.product_id).annotate(Min('price_from')).values(
                        'price_from').first()[
                        'price_from']
                trending_stock.append(stock)
                trending_stock_products_ids.append(stock.product.pk)
        trending_products_stock = len(trending_stock) > 1 and trending_stock[:10]
        for stock in trending_products_stock:
            calculate_new_prices(stock.product)
        # ---------------- Banners deals ----------------
        top_banners = Banner.objects.filter(is_active=True)[:2]
        # ---------------- Last Products ----------------
        last_products_ids = Stock.objects.filter(product__is_active=True).values('product').distinct().order_by('product__add_date').values('product')
        last_products = list()
        for p_id in last_products_ids:
            last_products.append(Product.objects.get(id=p_id['product']))
        calculate_new_prices(last_products)
        # ---------------- Featured Products (Produits Spéciales) featured=0..10  featured_products=10..20 ----------------
        featured_stock, featured_stock_products_ids = list(), list()
        for stock in Stock.objects.filter(product__is_featured=True, product__is_active=True).order_by(
                '-product__number_views'):
            if stock.product.pk not in featured_stock_products_ids:
                featured_stock.append(stock)
                featured_stock_products_ids.append(stock.product.pk)
        featured = featured_stock[:10] if len(featured_stock) > 0 else trending_stock
        featured_products = list()
        for stock in featured_stock:
            featured_products.append(stock.product)
        if len(featured_products) == 0:
            featured_products = featured - trending_stock if len(trending_stock) > 0 else Product.objects.filter(
                quantity__gt=0).distinct()
        calculate_new_prices(featured_products)
        # ---------------- Deals Of The Week 0..10 => 10..20 ----------------
        deals_of_week = sorted(
            Sale.objects.filter(is_daily=False, product__is_active=True, product__stock__isnull=False,
                                date_end__gt=now()), key=lambda deal: deal.saved_amount())
        deals_of_week.reverse()
        deals_of_week = list(deals_of_week)
        sales_deals_products_ids = list()
        final_deals_of_week = list()
        for deal in deals_of_week:
            if deal.product_id not in sales_deals_products_ids:
                stock = deal.product.stock_set.all()
                if stock.exists():
                    deal.product.price += stock.all().order_by('price_sup').first().price_sup
                deal.quantity = deal.product.stock_set.aggregate(Sum('quantity'))["quantity__sum"]
                deal.first_quantity = deal.product.stock_set.aggregate(Sum('first_quantity'))["first_quantity__sum"]
                deal.percent = (deal.quantity * 100) / deal.first_quantity
                deal.sold = deal.first_quantity - deal.quantity
                deal.consumed_percentage = str(((100 * deal.sold) / deal.first_quantity)).replace(',', '.')
                sales_deals_products_ids.append(deal.product_id)
                final_deals_of_week.append(deal)
        # ---------------- Random Categories ----------------
        bc = dict()
        categories = Category.objects.all()
        for category in categories:
            bc[category] = category.product_set.count()
        best_categories = [l[0] for l in sorted(list(bc.items()), key=lambda x: x[1])]
        best_categories.reverse()
        best_categories = best_categories[:3]
        # ---------------- Top 20 Products ----------------
        stock_best_products_ids = Stock.objects.filter(product__is_active=True).values('product').distinct().annotate(
            sold_percentage=(100 - (Sum(F('quantity')) * 100) / Sum(F('first_quantity')))).order_by(
            '-sold_percentage').values('product')
        best_products = list()
        for p_id in stock_best_products_ids:
            best_products.append(Product.objects.get(id=p_id['product']))
        calculate_new_prices(best_products)
        # ---------------- More Products Category ----------------
        more_products_category = Category.objects.annotate(Sum('product')).values('product__sum', 'id').order_by(
            '-product__sum').first()
        more_products_category['id'] = Category.objects.get(id=more_products_category['id'])
        more_products = more_products_category['id'].product_set.all()
        for product in more_products:
            calculate_new_prices(product)
            print(f'PRICE: {product.price}')

        context = {
            'trending_products_stock': trending_products_stock[:10],
            'last_products': last_products,
            'featured': featured,
            'deals_of_week': final_deals_of_week,
            'featured_products': featured_products,
            'best_categories': best_categories,
            'best_products': best_products[:4],
            'more_products': more_products,
            'more_products_category': more_products_category,
            'banners': top_banners,
        }
        return render(request, 'ecommerce/home.html', context)


def category(request, id):
    context = dict()
    return render(request, 'ecommerce/home.html')

# ---------------- Calculating Product Price Depending On Stock Sup Price And Sales ----------------
def calculate_new_prices(products, color=None):
    try:
        product_iterator = iter(products)
        for product in products:
            stock = product.stock_set.all()
            if stock.exists():
                if color is None:
                    product.price += stock.all().order_by('price_sup').first().price_sup
                else:
                    product.price += stock.filter(color=color).first().price_sup
            sale = product.sale_set.filter(date_end__gte=datetime.date.today())
            if sale.exists():
                product.is_sale = True
                product.old_price = product.price
                product.price -= sale.all().order_by('-percentage').first().saved_amount()
    except TypeError as te:
        product = products
        stock = product.stock_set.all()
        if stock.exists():
            if color is None:
                product.price += stock.all().order_by('price_sup').first().price_sup
            else:
                product.price += stock.filter(color=color).first().price_sup
        sale = product.sale_set.filter(date_end__gte=datetime.date.today())
        if sale.exists():
            product.is_sale = True
            product.old_price = product.price
            product.price -= sale.all().order_by('-percentage').first().saved_amount()


# ---------------- NEWSLETTER SUBSCRIBE ----------------
def subscribe_email(request):
    if request.method == "POST":
        email = request.POST.get('email')
        status = False
        msg = ""
        try:
            if request.user.email == email:
                NewsLetter.objects.create(email=email)
                message = render_to_string('ecommerce/mail/subscription.html', {'email': email})
                send_mail("NewsLetter Subscription", message, "haytham.dahri@ecommerce.ma", [email], fail_silently=False,  html_message=message)
                status = True
                msg = "Vous êtes inscrit au Newsletter, vous allez recevoir des notifications, Merci."

templates/ecommerce/accounts/sign_in_sign_up.html
{% extends "ecommerce/base.html" %}
{% load staticfiles %}
{% load humanize %}
{% load widget_tweaks %}

{% block title %}Mon compte{% endblock %}

{% block content %}
    <div id="content" class="site-content" tabindex="-1">
                <div class="container">

                    <nav class="woocommerce-breadcrumb" ><a href="{% url 'ecommerce:home' %}">Acceuil</a><span class="delimiter"><i class="fa fa-angle-right"></i></span>Mon Compte</nav><!-- .woocommerce-breadcrumb -->

                    <div class="content-area">
                        <main id="main" class="site-main">

                    {% include 'ecommerce/messages.html' %}

                            <article id="post-8" class="hentry">

                                <div class="entry-content">
                                    <div class="woocommerce">
                                        <div class="customer-login-form">
                                            <span class="or-text">Ou</span>

                                            <div class="col2-set" id="customer_login">


                                                <div class="col-1">


                                                    <h2>CONNEXION</h2>

                                                    <form method="post" class="login" action="{% url 'ecommerce:login' %}">
                                                        {% csrf_token %}

                                                        <p class="before-login-text">Bienvenue! Connecter avec votre compte</p>

                                                        <p class="form-row form-row-wide">
                                                            <label for="username">Email: <span class="required">*</span></label>
                                                            {% render_field LoginForm.email %}

                                                        </p>

                                                        <p class="form-row form-row-wide">
                                                            <label for="password">Mot de passe: <span class="required">*</span></label>
                                                            {% render_field LoginForm.password %}

                                                        </p>

                                                        <p class="form-row">
                                                            <button class="button" type="submit"><i class="fas fa-sign-in-alt"></i> Se connecter</button>
                                                        </p>

                                                        <p class="lost_password"><a href="{% url 'ecommerce:password_reset' %}">Mot de passe oublié?</a></p>

                                                    </form>


                                                </div><!-- .col-1 -->

                                                <div class="col-2">

                                                    <h2>CREER UN COMPTE</h2>

                                                    <form method="post" class="register" enctype="multipart/form-data">
                                                        {% csrf_token %}


                                                        <p class="before-register-text">Créer votre compte</p>

                                                        <p class="form-row form-row-wide">
                                                            <label for="username">Username<span class="required">*</span></label>
                                                            {% if SignUpForm.username.errors %}
                                                                {% render_field SignUpForm.username style='border: 1px solid red' %}
                                                            {% else %}
                                                                {% render_field SignUpForm.username %}
                                                            {% endif %}
                                                            {% for error in SignUpForm.username.errors %}
                                                                <small class="form-text text-muted text-danger" id="news_letter_helper" style="">
                                                                    <i class="fas fa-exclamation-triangle"></i> {{ error }}<br>
                                                                </small>
                                                            {% endfor %}
                                                        </p>
                                                        <p class="form-row form-row-wide">
                                                            <label for="username">Nom<span class="required">*</span></label>
                                                            {% if SignUpForm.first_name.errors %}
                                                                {% render_field SignUpForm.first_name style='border: 1px solid red' %}
                                                            {% else %}
                                                                {% render_field SignUpForm.first_name %}
                                                            {% endif %}
                                                            {% for error in SignUpForm.first_name.errors %}
                                                                <small class="form-text text-muted text-danger" id="news_letter_helper" style="">
                                                                    <i class="fas fa-exclamation-triangle"></i> {{ error }}<br>
                                                                </small>
                                                            {% endfor %}
                                                        </p>
                                                        <p class="form-row form-row-wide">
                                                            <label for="username">Prenom<span class="required">*</span></label>
                                                            {% if SignUpForm.last_name.errors %}
                                                                {% render_field SignUpForm.last_name style='border: 1px solid red' %}
                                                            {% else %}
                                                                {% render_field SignUpForm.last_name %}
                                                            {% endif %}
                                                            {% for error in SignUpForm.last_name.errors %}
                                                                <small class="form-text text-muted text-danger" id="news_letter_helper" style="">
                                                                    <i class="fas fa-exclamation-triangle"></i> {{ error }}<br>
                                                                </small>
                                                            {% endfor %}
                                                        </p>
                                                        <p class="form-row form-row-wide">
                                                            <label for="username">Adresse email<span class="required">*</span></label>
                                                            {% if SignUpForm.email.errors %}
                                                                {% render_field SignUpForm.email style='border: 1px solid red' %}
                                                            {% else %}
                                                                {% render_field SignUpForm.email %}
                                                            {% endif %}
                                                            {% for error in SignUpForm.email.errors %}
                                                                <small class="form-text text-muted text-danger" id="news_letter_helper" style="">
                                                                    <i class="fas fa-exclamation-triangle"></i> {{ error }}<br>
                                                                </small>
                                                            {% endfor %}
                                                        </p>
                                                        <p class="form-row form-row-wide">
                                                            <label for="username">Mot de passe<span class="required">*</span></label>
                                                            {% if SignUpForm.password.errors %}
                                                                {% render_field SignUpForm.password style='border: 1px solid red' %}
                                                            {% else %}
                                                                {% render_field SignUpForm.password %}
                                                            {% endif %}
                                                            {% for error in SignUpForm.password.errors %}
                                                                <small class="form-text text-muted text-danger" id="news_letter_helper" style="">
                                                                    <i class="fas fa-exclamation-triangle"></i> {{ error }}<br>
                                                                </small>
                                                            {% endfor %}
                                                        </p>

                                                        <p class="form-row">
                                                            <button class="button" type="submit"><i class="fas fa-user-plus"></i> S'inscrir</button>
                                                        </p>

                                                        <div class="register-benefits">
                                                            <h3>Inscrivez-vous aujourd'hui et vous pourrez :</h3>
                                                            <ul>
                                                                <li>Acheter des produits de promo</li>
                                                                <li>Suivri des commandes</li>
                                                                <li>Garder l'historique des achats</li>
                                                            </ul>
                                                        </div>

                                                    </form>

                                                </div><!-- .col-2 -->

                                            </div><!-- .col2-set -->

                                        </div><!-- /.customer-login-form -->
                                    </div><!-- .woocommerce -->
                                </div><!-- .entry-content -->

                            </article><!-- #post-## -->

                        </main><!-- #main -->
                    </div><!-- #primary -->

                </div><!-- .col-full -->
            </div><!-- #content -->
{% endblock %}

templates/ecommerce/accounts/singup_thanks.html
{% extends 'ecommerce/base.html' %}
{% load staticfiles %}

{% block title %}COMPTE ACTIVÉ{% endblock %}

{% block content %}

            <h1 style="padding: 25px; text-align: center;width: 100%;">VOTRE COMPTE À ÉTÉ ACTIVÉ, MERCI.</h1>

{% endblock %}
{% block js %}
    {{ block.super }}

    <script>

        $("body").attr('class','page home page-template-default');
        $('img[product="wishlist-product"]').css({'height': '100', 'height': '100'});
    </script>

{% endblock %}